
The `<links>` configuration contains a list of containers that should
be linked to this container according to https://docs.docker.com/userguide/dockerlinks[Docker Links]. Each link can have two parts where the optional right side is separated by a `:` and will be used as the name in the environment variables and the left side refers to the name of the container linking to. This is equivalent to the linking when using the Docker CLI `--link` option.

Example for linking to a container with name or alias _postgres_ :

.Example
[source,xml]
----
<links>
  <link>postgres:db</link>
</links>
----

This will create the following environment variables, given that the postgres image exposes TCP port 5432:

.Example
[source,bash]
----
DB_NAME=/web2/db
DB_PORT=tcp://172.17.0.5:5432
DB_PORT_5432_TCP=tcp://172.17.0.5:5432
DB_PORT_5432_TCP_PROTO=tcp
DB_PORT_5432_TCP_PORT=5432
DB_PORT_5432_TCP_ADDR=172.17.0.5
----

Additionally, each `<link>` element can specify a comma separated set of links.  Comma (and whitespace) can be used to separate links since valid docker link names/aliases contain only characters, digits, underscores, periods and dashes.

.Example
[source,xml]
----
<links>
  <link>postgres:db, search, saml:identity</link>
</links>
----

If you wish to link to existing containers not managed by the plugin, you may do so by specifying the container name obtained via `docker ps` in the configuration.

Please note that the link behaviour also depends on the network mode selected. Links as described are referred to by Docker as _legacy links_ and might vanish in the future. For custom networks no environments variables are set and links create merely network aliases for the linked container. To express start order dependencies using custom networks refer to the <<start-depends-on,dependsOn>> configuration.

For a more detailed documentation for the new link handling please refer to the https://docs.docker.com/engine/userguide/networking/work-with-networks/#linking-containers-in-user-defined-networks[Docker network documentation]
