
A container can bind (or "mount") volumes from various source when starting up: Either from a directory of the host system or from another container which exports one or more directories. The mount configuration is specified within a `<volumes>` section of the run configuration. It can contain the following sub elements:

.Volume configuration
[cols="1,5"]
|===
| Element | Description

| *from*
| List of `<image>` elements which specify image names or aliases of containers whose volumes should be imported.

| *bind*
| List of `<volume>` specifications (or _host mounts_). Use `/path` to create and expose a new volume in the container, `/host_path:/container_path` to mount a host path into the container and `/host_path:/container_path:ro` to bind it read-only.
|===

.Volumes example
[source,xml]
----
<volumes>
  <bind>
    <volume>/logs</volume>
    <volume>/opt/host_export:/opt/container_import</volume>
  </bind>
  <from>
    <image>jolokia/docker-demo</image>
  </from>
</volumes>
----

In this example the container creates a new volume named  `/logs` on the container and mounts `/opt/host_export` from the host as `/opt/container_import` on the container. In addition all exported volumes from the container which has been created from the image `jolokia/docker-demo` are mounted directly into the container (with the same directory names under which the exporting container exposes these directories). This image must be also configured for this plugin. Instead of the full image name, an alias name can be used, too.

Please note, that no relative paths are allowed. However, you can use Maven variables in the path specifications. This should even work for boot2docker and docker-machine:

.Example with absolute paths
[source,xml]
----
<volumes>
  <bind>
    <volume>${project.build.directory}/${project.artifactId}-${project.version}:/usr/local/tomcat/webapps/${project.name}</volume>
    <volume>${project.basedir}/data:/data</volume>
  </bind>
</volumes>
----

If you wish to mount volumes from an existing container not managed by the plugin, you may do by specifying the container name obtained via `docker ps` in the configuration.
