
[[docker:save]]
== *docker:save*

The `{plugin}:save` target saves an image defined in the build configuration to a local file, analogous to `docker save`.
If the option `saveFile` is not set, the file name is calculated automatically:

* If `saveAlias` is used then the file is stored as `target/<alias>-<project version>.tar.gz`
* Otherwise the archive is stored as `target/<image name without registry and user part>-<image tag>.tar.gz`

Please note that the exported image contains all image layers and can be quite large (also, it takes a bit to export the image).

.Save options
[cols="1,5,1"]
|===
| Element | Description | Property

| *saveName*
| The name of the image configuration to save. Must not be used together with `alias`.
| `docker.save.name`

| *saveAlias*
| The alias of the image configuration to save. Must not be used together with `name`.
| `docker.save.alias`

| *saveFile*
| The filename to save.
| `docker.save.file` or `docker.file` or `file`

| *skipSave*
| A boolean flag whether to skip execution of the goal.
| `docker.skip.save`
|===
