
[[docker:remove]]
== *docker:remove*

This goal can be used to clean up images. By default all images with a build configuration are removed.
You can tune this by setting the property `removeMode` (property: `docker.removeMode`) to one of the following values:

.removeMode Values
[cols="1,5"]
|===
| Value | Description

| `build`
| All images with a <<build-configuration,build configuration>>

| `run`
| All images without a <<start-configuration,build configuration>>

| `all`
| All configured images

| `data`
| All data images, which are images without a <<start-configuration,run configuration>>.
|===

Previously, this could be tuned also by providing the property `removeAll` which indicates to remove all images managed by this build. Otherwise only data images were delete before 0.24.0. `removeAll` is deprecated and will be removed soone. Please use `removeMode` instead.

As with the other goals, the configuration `image` can be used to tune the images to remove. All containers belonging to the images are removed as well as the all tags assigned to this image

Considering three images 'db','tomcat' and 'data' where 'data' is the only image with a build configuration:

* `mvn {plugin}:remove` will remove 'data'
* `mvn -Ddocker.removeMode=all {plugin}:remove` will remove all three images
* `mvn -Ddocker.filter=data,tomcat {plugin}:remove` will remove 'data'
* `mvn -Ddocker.filter=data,tomcat -Ddocker.removeMode=all {plugin}:remove` will remove 'data' and 'tomcat'

.Remove options
[cols="1,5,1"]
|===
| Element | Description | Property

| *skipTag*
| If set to `true` this plugin won't remove any tags
| `docker.skip.tag`

| *removeNamePattern*
| If a list of <<name-patterns, name patterns>> is provided, any images matching the patterns will be removed,
independently of whether there is an <<image-configuration, image configuration>> marked for removal.
| `docker.removeNamePattern`
|===