
[[docker:build]]
== **docker:build**

This goal will build all images which have a `<build>` configuration section, or, if the global configuration variable `image` (property:
`docker.image`) is set, only the images contained in this variable (comma separated) will be built.

Image can be build in two different ways:

.Inline plugin configuration
With an inline plugin configuration all information required to build the image is contained in the plugin configuration. By default its the standard XML based configuration for the plugin but can be switched to a property based configuration syntax as described in the section <<external-configuration,External configuration>>. The XML configuration syntax is recommended because of its more structured and typed nature.

When using this mode, the Dockerfile is created on the fly with all instructions extracted from the configuration given.

.External Dockerfile
Alternatively an external Dockerfile template can be used. This mode is switch on by using one of these two configuration options within
the `<build>` configuration section.

* *dockerFileDir* specifies a directory containing a `Dockerfile` that will be used to create the image.
* *dockerFile* specifies a specific Dockerfile. The `dockerFileDir` is set to the directory containing the file.

If `dockerFileDir` is a relative path looked up in `${project.basedir}/src/main/docker`. You can make easily an absolute path by prefixing with `${project.basedir}`.

Any additional files located in the `dockerFileDir` directory will also be added to the build context as well as any files specified by an assembly. However, you still need to insert `ADD` or `COPY` directives yourself into the Dockerfile.

If this directory contains a `.maven-dockerignore` (or alternatively, a `.maven-dockerexclude` file), then it is used for excluding files for the build. Each line in this file is treated as an http://ant.apache.org/manual/Types/fileset.html[FileSet exclude pattern] as used by the http://maven.apache.org/plugins/maven-assembly-plugin[maven-assembly-plugin]. It is similar to `.dockerignore` when using Docker but has a slightly different syntax (hence the different name).

If this directory contains a `.maven-dockerinclude` file, then it is used for including only those files for the build. Each line in this file is also treated as an http://ant.apache.org/manual/Types/fileset.html[FileSet exclude pattern] as used by the http://maven.apache.org/plugins/maven-assembly-plugin[maven-assembly-plugin].

Except for the <<assembly,assembly configuration>> all other configuration options are ignored for now.

****
For the future it is
planned to introduce special keywords lile `DMP_ADD_ASSEMBLY` which
can be used in the Dockerfile template to placing the configuration
resulting from the additional configuration.
****

The following example uses a Dockerfile in the directory
`src/main/docker/demo`:

[source,xml]
----
<plugin>
 <configuration>
   <images>
     <image>
       <name>user/demo</name>
       <build>
         <dockerFileDir>demo</dockerFileDir>
       </build>
     </image>
   </images>
 </configuration>
 ...
</plugin>
----

[[build-config]]
=== Configuration

All build relevant configuration is contained in the `<build>` section
of an image configuration. In addition to `<dockerFileDir>` and
`<dockerFile>` the following configuration options are available:

.Build configuration
[cols="1,5"]
|===
| Element | Description

| *args*
| Map specifying the value of https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg[Docker build args]
which should be used when building the image with an external Dockerfile which uses build arguments. The key-value syntax is the same as when defining Maven properties (or `labels` or `env`).
This argument is ignored when no external Dockerfile is used. Build args can also be specified as properties as
described in <<build-args,Build Args>>

| *assembly*
| specifies the assembly configuration as described in <<assembly,Build Assembly>>

| *cleanup*
| Cleanup dangling (untagged) images after each build (including any containers created from them). Default is `try` which tries to remove the old image, but doesn't fail the build if this is not possible because e.g. the image is still used by a running container. Use `remove` if you want to fail the build and `none` if no cleanup is requested.

| *nocache*
| Don't use Docker's build cache. This can be overwritten by setting a system property `docker.nocache` when running Maven.

| *cmd*
| A command to execute by default (i.e. if no command is provided when a container for this image is started). See <<startup,Startup Arguments>> for details.

| *entryPoint*
| An entrypoint allows you to configure a container that will run as an executable. See <<startup,Startup Arguments>> for details.

| *env*
| The environments as described in <<env,Setting Environment Variables and Labels>>.

| *from*
| The base image which should be used for this image. If not given this default to `busybox:latest` and is suitable for a pure data image.

| *labels*
| Labels  as described in <<env,Setting Environment Variables and Labels>>.

| *maintainer*
| The author (`MAINTAINER`) field for the generated image

| *ports*
| The exposed ports which is a list of `<port>` elements, one for each port to expose.

| *runCmds*
| Commands to be run during the build process. It contains *run* elements which are passed to the shell. The run commands are inserted right after the assembly and after *workdir* in to the Dockerfile. This tag is not to be confused with the `<run>` section for this image which specifies the runtime behaviour when starting containers.

| *optimise*
| if set to true then it will compress all the `runCmds` into a single `RUN` directive so that only one image layer is created.

| *compression*
| The compression mode how the build archive is transmitted to the docker daemon (`docker:build`) and how docker build archives are attached to this build as sources (`docker:source`). The value can be `none` (default), `gzip` or `bzip2`.

| *skip*
| if set to true disables building of the image. This config option is best used together with a maven property

| *tags*
| List of additional `tag` elements with which an image is to be tagged after the build.

| *user*
| User to which the Dockerfile should switch to the end (corresponds to the `USER` Dockerfile directive).

| *volumes*
| List of `volume` elements to create a container volume.

| *workdir*
| Directory to change to when starting the container.
|===

From this configuration this Plugin creates an in-memory Dockerfile,
copies over the assembled files and calls the Docker daemon via its
remote API.

Here's an example:

[source,xml]
----
<build>
  <from>java:8u40</from>
  <maintainer>john.doe@example.com</maintainer>
  <tags>
    <tag>latest</tag>
    <tag>${project.version}</tag>
  </tags>
  <ports>
    <port>8080</port>
  </ports>
  <volumes>
    <volume>/path/to/expose</volume>
  </volumes>

  <entryPoint>
    <!-- exec form for ENTRYPOINT -->
    <exec>
      <arg>java</arg>
      <arg>-jar</arg>
      <arg>/opt/demo/server.jar</arg>
    </exec>
  </entryPoint>

  <assembly>
    <mode>dir</mode>
    <basedir>/opt/demo</basedir>
    <descriptor>assembly.xml</descriptor>
  </assembly>
</build>
----

[[assembly]]
=== Assembly

The `<assembly>` element within `<build>` is has an XML struture and defines how build artifacts and other files can enter the Docker image.

.Assembly Configuration
[cols="1,5"]
|===
| Element | Description

| *basedir*
| Directory under which the files and artifacts contained in the assembly will be copied within the container. The default value for this is `/maven`.

| *inline*
| Inlined assembly descriptor as described in <<assembly-descriptor,Assembly Descriptor>> below.

| *descriptor*
| Path to an assembly descriptor file, whose format is described  <<assembly-descriptor,Assembly Descriptor>> below.

| *descriptorRef*
| Alias to a predefined assembly descriptor. The available aliases are also described in <<assembly-descriptor,Assembly Descriptor>> below.

| *dockerFileDir*
| Directory containing an external Dockerfile. _This option is deprecated, please use <dockerfiledir> directly in the <build> section.

| *exportBasedir*
| Specification whether the `basedir` should be exported as a volume.  This value is `true` by default except in the case the `basedir` is set to the container root (`/`). It is also `false` by default when a base image is used with `from` since exporting makes no sense in this case and will waste disk space unnecessarily.

| *ignorePermissions*
| Specification if existing file permissions should be ignored
when creating the assembly archive with a mode `dir`. This value is `false` by default. _This property is deprecated, use a `permissionMode` of `ignore` instead._

| *mode*
a| Mode how the how the assembled files should be collected:

* `dir` : Files are simply copied (default),
* `tar` : Transfer via tar archive
* `tgz` : Transfer via compressed tar archive
* `zip` : Transfer via ZIP archive

The archive formats have the advantage that file permission can be preserved better (since the copying is independent from the underlying files systems), but might triggers internal bugs from the Maven assembler (as it has been reported in https://github.com/fabric8io/docker-maven-plugin/issues/171[#171])

| *permissions*
a| Permission of the files to add:

* `ignore` to use the permission as found on files regardless on any
assembly configuration
* `keep` to respect the assembly provided permissions, `exec` for setting the executable bit on all files (required for Windows when using an assembly mode `dir`)
* `auto` to let the plugin select `exec` on Windows and `keep` on others.

`keep` is the default value.

| *user*
| User and/or group under which the files should be added. The user must already exist in the base image.

It has the general format `user[:group[:run-user]]`. The user and group can be given either as numeric user- and group-id or as names. The group id is optional.

If a third part is given, then the build changes to user `root` before changing the ownerships, changes the ownerships and then change to user `run-user` which is then used for the final command to execute. This feature might be needed, if the base image already changed the user (e.g. to 'jboss') so that a `chown` from root to this user would fail.

For example, the image `jboss/wildfly` use a "jboss" user under which all commands are executed. Adding files in Docker always happens under the UID root. These files can only be changed to "jboss" is the `chown` command is executed as root. For the following commands to be run again as "jboss" (like the final `standalone.sh`), the plugin switches back to user `jboss` (this is this "run-user") after changing the file ownership. For this example a specification of
`jboss:jboss:jboss` would be required.
|===

In the event you do not need to include any artifacts with the image, you may safely omit this element from the configuration.

[[assembly-descriptor]]
==== Assembly Descriptor

With using the `inline`, `descriptor` or `descriptorRef` option
it is possible to bring local files, artifacts and dependencies into
the running Docker container. A `descriptor` points to a file
describing the data to put into an image to build. It has the same
http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html[format] as for creating assemblies with the
http://maven.apache.org/plugins/maven-assembly-plugin[maven-assembly-plugin] with following exceptions:

* `<formats>` are ignored, the assembly will allways use a directory
when preparing the data container (i.e. the format is fixed to
`dir`)
* The `<id>` is ignored since only a single assembly descriptor is
used (no need to distinguish multiple descriptors)

Also you can inline the assembly description with a `inline` description
directly into the pom file. Adding the proper namespace even allows for
IDE autocompletion. As an example, refer to the profile `inline` in
the `data-jolokia-demo`'s pom.xml.

Alternatively `descriptorRef` can be used with the name of a
predefined assembly descriptor. The following symbolic names can be
used for `descriptorRef`:

.Predefined Assembly Descriptors
[cols="1,3"]
|===
| Assembly Reference | Description

| *artifact-with-dependencies*
| Attaches project's artifact and all its dependencies. Also, when a `classpath` file exists in the target directory, this will be added to.

| *artifact*
| Attaches only the project's artifact but no dependencies.

| *project*
| Attaches the whole Maven project but with out the `target/` directory.

| *rootWar*
| Copies the artifact as `ROOT.war` to the exposed directory. I.e. Tomcat will then deploy the war under the root context.
|===
For example,

[source,xml]
----
<images>
  <image>
    <build>
      <assembly>
         <descriptorRef>artifact-with-dependencies</descriptorRef>
         .....
----

will add the created artifact with the name `${project.build.finalName}.${artifact.extension}` and all jar dependencies in the the `baseDir` (which is `/maven` by default).

All declared files end up in the configured `basedir` (or `/maven` by default) in the created image.

If the assembly references the artifact to build with this pom, it is required that the `package` phase is included in the run. This happens either automatically when the `docker:build` target is called as part of a binding (e.g. is `docker:build` is bound to the `pre-integration-test`
phase) or it must be ensured when called on the command line:

[source,sh]
----
mvn package docker:build
----

This is a general restriction of the Maven lifecycle which applies also
for the `maven-assembly-plugin` itself.

In the following example a dependency from the pom.xml is included and
mapped to the name `jolokia.war`. With this configuration you will end
up with an image, based on `busybox` which has a directory `/maven`
containing a single file `jolokia.war`. This volume is also exported
automatically.

[source,xml]
----
<assembly>
  <dependencySets>
    <dependencySet>
      <includes>
        <include>org.jolokia:jolokia-war</include>
      </includes>
      <outputDirectory>.</outputDirectory>
      <outputFileNameMapping>jolokia.war</outputFileNameMapping>
    </dependencySet>
  </dependencySets>
</assembly>
----

Another container can now connect to the volume an 'mount' the
`/maven` directory. A container  from `consol/tomcat-7.0` will look
into `/maven` and copy over everything to `/opt/tomcat/webapps` before
starting Tomcat.

If you are using the `artifact` or `artifact-with-dependencies` descriptor, it is
possible to change the name of the final build artifact with the following:

[source,xml]
----
<build>
  <finalName>your-desired-final-name</finalName>
  ...
</build>
----

Please note, based upon the following documentation listed http://maven.apache.org/pom.html#BaseBuild_Element[here], there is no guarantee the plugin creating your artifact will honor it in which case you will need to use a custom descriptor like above to achieve the desired naming.

Currently the `jar` and `war` plugins properly honor the usage of `finalName`.

[[startup]]
=== Startup Arguments

Using `entryPoint` and `cmd` it is possible to specify the https://docs.docker.com/reference/builder/#entrypoint[entry point]
or https://docs.docker.com/reference/builder/#cmd[cmd] for a container.

The difference is, that an `entrypoint` is the command that always be executed, with the `cmd` as argument. If no `entryPoint` is provided, it defaults to `/bin/sh -c` so any `cmd` given is executed with a shell. The arguments given to `docker run` are always given as arguments to the
`entrypoint`, overriding any given `cmd` option. On the other hand if no extra arguments are given to `docker run` the default `cmd` is used as argument to `entrypoint`.

****
See this http://stackoverflow.com/questions/21553353/what-is-the-difference-between-cmd-and-entrypoint-in-a-dockerfile[stackoverflow question] for a detailed explanation.
****

A entry point or command can be specified in two alternative formats:

.Entrypoint and Command Configuration
[cols="1,5"]
|===
| Mode | Description

| *shell*
| Shell form in which the whole line is given to `shell -c` for interpretation.

| *exec*
| List of arguments (with inner `<args>`) arguments which will be given to the `exec` call directly without any shell interpretation.
|===

Either shell or params should be specified.

Example:

[source,xml]
----
<entryPoint>
   <!-- shell form  -->
   <shell>java -jar $HOME/server.jar</shell>
</entryPoint>
----

or

[source,xml]
----
<entryPoint>
   <!-- exec form  -->
   <exec>
     <args>java</args>
     <args>-jar</args>
     <args>/opt/demo/server.jar</args>
   </exec>
</entryPoint>
----

This can be formulated also more dense with:

[source,xml]
----
<!-- shell form  -->
<entryPoint>java -jar $HOME/server.jar</entryPoint>
----

or

[source,xml]
----
<entryPoint>
  <!-- exec form  -->
  <arg>java</arg>
  <arg>-jar</arg>
  <arg>/opt/demo/server.jar</arg>
</entryPoint>
----

[[build-args]]
=== Build Args

As described in section <<build-config,Configuration>> for external Dockerfiles https://docs.docker.com/engine/reference/commandline/build/#set-build-time-variables-build-arg[Docker build arg] can be used. In addition to the
configuration within the plugin configuration you can also use properties to specify them:

* Set a system property when running Maven, eg.: `-Ddocker.buildArg.http_proxy=http://proxy:8001`. This is especially
useful when using predefined Docker arguments for setting proxies transparently.
* Set a project property within the `pom.xml`, eg.:

[source,xml]
----
  <docker.buildArg.myBuildArg>myValue</docker.buildArg.myBuildArg>
----

Please note that the system property setting will always override the project property. Also note that for all properties which are not Docker https://docs.docker.com/engine/reference/builder/#arg[predefined] properties, the external Dockerfile must contain an `ARGS` instruction.
