
[[docker:save]]
== *docker:save*

The `{plugin}:save` target saves an image defined in the build configuration to a local file, analogous to `docker save`.
If the option `saveFile` is not set, the file name is calculated automatically:

* If `saveAlias` is used then the file is stored as `target/<alias>-<project version>.tar.gz`
* Otherwise the archive is stored as `target/<image name without registry and user part>-<image tag>.tar.gz`

Please note that the exported image contains all image layers and can be quite large (also, it takes a bit to export the image).

.Controlling image compression
The file name extension is used to select a compression method for the output.
[cols="3,2,1"]
|===
| Extensions | Compression | Type

| .tar or unrecognized
| No compression
| .tar

| .tar.gz, .tgz
| GZIP compression
| .tar.gz

| .tar.bz, .tar.bz2, .tar.bzip2
| BZIP2 compression
| .tar.bz

|===

.Attaching the saved image as an artifact
If `saveClassifier` is set, the saved archive will be attached to the project using the provided classifier and the type determined from the file name. The placeholder `%a` will be replaced with the image alias.

Note that using overriding the default to use `docker` or `docker-%a` may lead to a conflict if a source archive is also attached with <<{plugin}:source>>.

.Save options
[cols="1,5,1"]
|===
| Element | Description | Property

| *saveName*
| The name of the image configuration to save. Must not be used together with `alias`.
| `docker.save.name`

| *saveAlias*
| The alias of the image configuration to save. Must not be used together with `name`.
| `docker.save.alias`

| *saveFile*
| The filename to save.
| `docker.save.file` or `docker.file` or `file`

| *saveClassifier*
| If set, attach the the saved archive to the project with the provided classifier. A placeholder of `%a` will be replaced with the image alias.
| `docker.save.classifier`

| *skipSave*
| A boolean flag whether to skip execution of the goal.
| `docker.skip.save`
|===
