
[[docker:stop]]
== *docker:stop*

Stops and removes a docker container. This goal stops every container started with `<{plugin}:start>` either during the same build (e.g. when bound to lifecycle phases when doing integration tests) or for containers created by a previous call to `<{plugin}:start>`

If called within the same build run, only the containers that were explicitly started during the run will be stopped. Existing containers started using `{plugin}:start` for the project will not be affected.

If called as a separate invocation, the plugin will stop and remove any container it finds whose image is defined in the project's configuration. Any existing containers found running whose image name matches but were not started by the plugin will not be affected.

In case the naming strategy for an image is `alias` (i.e. the container name is set to the given alias), then only the container with this alias is stopped. Other containers originating from the same image are not touched.

It should be noted that any containers created prior to version `0.13.7` of the plugin may not be stopped correctly by the plugin because the label needed to tie the container to the project may not exist. Should this happen, you will need to use the Docker CLI to clean up the containers and/or use the `docker.allContainers` option listed below.

For tuning what should happen when stopping there are four global parameters which are typically used as system properties:
`allContainers`, `keepContainer`, `keepRunning` and `removeVolumes`.

.Stop configuration
[cols="1,5,1"]
|===
| Element | Description | Parameter

| *allContainers*
| Stops and removes any container that matches an image defined in the current project's configuration. This was the default behavior of the plugin prior up to version 0.13.6
| `docker.allContainers`

| <<container-name, *containerNamePattern*>>
| Default pattern that <<{plugin}:start>> uses for naming containers when they are created. See <<container-name, Container Names>> for details.
This should match the setting for <<{plugin}:start>> goals if the goals are configured in separate executions.
| `docker.containerNamePattern`

| *keepContainer*
| If set to `true` not destroy container after they have been stopped. Default is false.
| `docker.keepContainer`

| *keepRunning*
| If set to `true` actually don't stop the container. This apparently makes only sense when used on the command line when doing integration testing (i.e. calling `{plugin}:stop` during a lifecycle binding) so that the container are still running after an integration test. This is useful for analysis of the containers (e.g. by entering it with `docker exec`).
| `docker.keepRunning`

| *removeVolumes*
| If set to `true` will remove any volumes associated to the container as well. This option will be ignored if either `keepContainer` or `keepRunning` are true.
| `docker.removeVolumes`

| *stopNamePattern*
| If a list of <<name-patterns, name patterns>> is provided, any containers matching the patterns will be stopped and
removed (depending on the values of `keepContainer` and `keepRunning`),
independently of whether there is an <<image-configuration, image configuration>>.
| `docker.stopNamePattern`
|===

.Example
[source,sh]
----
$ mvn -Ddocker.keepRunning clean install
----
