name: Documentation Build

on:
  push:
    branches:
      - dmp.fabric8.io

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Documentation Build on Java ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build Project
        run: |
          mvn -Pdoc-html && mvn -Pdoc-pdf
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3    
        with:
          path: ./target/generated-docs
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
