name: E2E Windows

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 1 * * *' # Every day at 1

permissions:
  contents: read

jobs:
  windows-build:
    name: Windows
    runs-on: windows-latest
    steps:
      - name: Get Windows Version > Used to retrieve specific Docker Image
        shell: cmd
        run: |
          ver
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install DMP
        run: mvn ${MAVEN_ARGS} clean install -DskipTests
      - name: Run Integration tests
        run: |
          cd it/windows-build
          mvn clean install -Pwindows
