name: Release to SNAPSHOTS Maven Central

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e ${{ github.event.inputs.additional_args }}
  RELEASE_MAVEN_ARGS: -Prelease -Denforcer.skip=true
  OSSRHUSERNAME: ${{ secrets.OSSRHUSERNAME }}
  OSSRHPASSWORD: ${{ secrets.OSSRHPASSWORD }}
  SIGNINGPASSWORD: ${{ secrets.SIGNINGPASSWORD }}

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *' # Every day at 2am

jobs:
  release-snapshots:
    name: Release SNAPSHOT
    # Cheap way to prevent accidental releases
    # Modify the list to add users with release permissions
    if: contains('["rhuss","rohanKanojia"]', github.actor)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
          server-id: sonatype-nexus-snapshots
          server-username: OSSRHUSERNAME
          server-password: OSSRHPASSWORD
          gpg-private-key: ${{ secrets.SIGNINGKEY }}
          gpg-passphrase: SIGNINGPASSWORD
      - name: Build and Release Project
        run: ./mvnw ${MAVEN_ARGS} ${RELEASE_MAVEN_ARGS} clean deploy
