name: Windows Maven Wrapper Build

env:
  MAVEN_ARGS: -B -C -V -ntp -Dhttp.keepAlive=false -e

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    name: Windows Java ${{ matrix.java }} Maven Wrapper
    runs-on: windows-latest
    strategy:
      matrix:
        java: [11]
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Build Project
        run: ./mvnw.cmd %MAVEN_ARGS% clean install
